### PR TITLE
TS-69 unique 제약조건 추가

### PR DESCRIPTION
**Pull request by leebuwon**
- [x] steamId에 unique 제약 조건 추가

---

Co-authored-by: tkdtn4657 <tkdtn101226@gmail.com>
Co-authored-by: LeeYulhee <reasonoflife39@gmail.com>
Co-authored-by: hg0710 <hom0726@naver.com>
Co-authored-by: wooqqq <sge0225@naver.com>

### CODE REVIEW

**Review by LeeYulhee — APPROVED** [review]
고생하셨습니다

**Review by tkdtn4657 — APPROVED** [review]
고생하셨습니다!

**Review by wooqqq — APPROVED** [review]
고생하셨습니다!

**Review by hg0710 — APPROVED** [review]
고생하셨습니다!!

**Pull request merged**
